# Form implementation generated from reading ui file 'ui/app_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 450)
        Form.setStyleSheet("QWidget {\n"
"background-color: \"#FFF1DC\"\n"
"\n"
"}")
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(40, 80, 201, 21))
        self.lineEdit.setStyleSheet("QWidget {\n"
"    background-color: \"white\"\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(40, 50, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(310, 50, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 80, 201, 21))
        self.lineEdit_2.setStyleSheet("QWidget {\n"
"    background-color: \"white\"\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(40, 160, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(40, 200, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(parent=Form)
        self.comboBox.setGeometry(QtCore.QRect(130, 200, 69, 22))
        self.comboBox.setStyleSheet("QWidget {\n"
"    background-color: \"white\"\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(40, 240, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox_2 = QtWidgets.QComboBox(parent=Form)
        self.comboBox_2.setGeometry(QtCore.QRect(130, 240, 69, 22))
        self.comboBox_2.setStyleSheet("QWidget {\n"
"    background-color: \"white\"\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(40, 280, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.comboBox_3 = QtWidgets.QComboBox(parent=Form)
        self.comboBox_3.setGeometry(QtCore.QRect(130, 280, 69, 22))
        self.comboBox_3.setStyleSheet("QWidget {\n"
"    background-color: \"white\"\n"
"}")
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(40, 320, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBox_4 = QtWidgets.QComboBox(parent=Form)
        self.comboBox_4.setGeometry(QtCore.QRect(130, 320, 69, 22))
        self.comboBox_4.setStyleSheet("QWidget {\n"
"    background-color: \"white\"\n"
"}")
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_8 = QtWidgets.QLabel(parent=Form)
        self.label_8.setGeometry(QtCore.QRect(40, 360, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.comboBox_5 = QtWidgets.QComboBox(parent=Form)
        self.comboBox_5.setGeometry(QtCore.QRect(130, 360, 69, 22))
        self.comboBox_5.setStyleSheet("QWidget {\n"
"    background-color: \"white\"\n"
"}")
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setGeometry(QtCore.QRect(40, 400, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.comboBox_6 = QtWidgets.QComboBox(parent=Form)
        self.comboBox_6.setGeometry(QtCore.QRect(130, 400, 69, 22))
        self.comboBox_6.setStyleSheet("QWidget {\n"
"    background-color: \"white\"\n"
"}")
        self.comboBox_6.setObjectName("comboBox_6")
        self.label_10 = QtWidgets.QLabel(parent=Form)
        self.label_10.setGeometry(QtCore.QRect(310, 160, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(310, 190, 281, 21))
        self.lineEdit_4.setStyleSheet("QWidget {\n"
"    background-color: \"white\"\n"
"}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_11 = QtWidgets.QLabel(parent=Form)
        self.label_11.setGeometry(QtCore.QRect(310, 260, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(380, 400, 141, 31))
        self.pushButton.setStyleSheet("QWidget {\n"
"    background-color: \"white\"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.checkBox = QtWidgets.QCheckBox(parent=Form)
        self.checkBox.setGeometry(QtCore.QRect(310, 220, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_2.setGeometry(QtCore.QRect(310, 300, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.comboBox_7 = QtWidgets.QComboBox(parent=Form)
        self.comboBox_7.setGeometry(QtCore.QRect(130, 120, 69, 22))
        self.comboBox_7.setStyleSheet("QWidget {\n"
"    background-color: \"white\"\n"
"}")
        self.comboBox_7.setObjectName("comboBox_7")
        self.label_12 = QtWidgets.QLabel(parent=Form)
        self.label_12.setGeometry(QtCore.QRect(40, 120, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.comboBox_8 = QtWidgets.QComboBox(parent=Form)
        self.comboBox_8.setGeometry(QtCore.QRect(478, 340, 111, 22))
        self.comboBox_8.setStyleSheet("QWidget {\n"
"    background-color: \"white\"\n"
"}")
        self.comboBox_8.setObjectName("comboBox_8")
        self.label_13 = QtWidgets.QLabel(parent=Form)
        self.label_13.setGeometry(QtCore.QRect(310, 340, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "JoJo Stand Screen Maker"))
        self.lineEdit.setWhatsThis(_translate("Form", "Enter Stand Name"))
        self.label.setText(_translate("Form", "Stand Name:"))
        self.label_2.setText(_translate("Form", "Stand User Name:"))
        self.lineEdit_2.setWhatsThis(_translate("Form", "Enter Stand Name"))
        self.label_3.setText(_translate("Form", "Stand Stats:"))
        self.label_4.setText(_translate("Form", "Power"))
        self.label_5.setText(_translate("Form", "Speed"))
        self.label_6.setText(_translate("Form", "Range"))
        self.label_7.setText(_translate("Form", "Durability"))
        self.label_8.setText(_translate("Form", "Precision"))
        self.label_9.setText(_translate("Form", "Potential"))
        self.label_10.setText(_translate("Form", "Image File Path:"))
        self.lineEdit_4.setWhatsThis(_translate("Form", "Enter Stand Name"))
        self.label_11.setText(_translate("Form", "Background:"))
        self.pushButton.setText(_translate("Form", "Create Image"))
        self.checkBox.setText(_translate("Form", "Scale Image"))
        self.checkBox_2.setText(_translate("Form", "Use Default Background Color"))
        self.label_12.setText(_translate("Form", "Text Color"))
        self.label_13.setText(_translate("Form", "Background Color"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
